spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbevertec
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true